def awsECRURL="266852548854.dkr.ecr.ap-northeast-2.amazonaws.com/mini-project"
def awsKey="aws-key"
def awsRegion="ap-northeast-2"
def branch="main"
def commitMsg="Mini Project CI/CD Pipeline Job"
def directoryPath="Part4_Kubernetes/Chapter11/mini-project/service"
def githubEmail="shlee3048@naver.com"
def githubKey="github-key"
def githubSSHURL="git@github.com:shlee3048/FastCampus.git"
def imageTag="blue"

node {
    stage('Checkout') {
        checkout scm
    }

    stage('Docker Build') {
        dir(path: "${directoryPath}/container") {
            sh "docker buildx build --platform=linux/amd64 --build-arg COLOR=${imageTag} -t ${awsECRURL}:${imageTag} ./"
        }
    }

    stage('ECR Push') {
        docker.withRegistry("https://${awsECRURL}", "ecr:${awsRegion}:${awsKey}") {
            sh "docker push ${awsECRURL}:${imageTag}"
        }
    }

    stage('Deploy') {
        git branch: "${branch}",
            credentialsId: "${githubKey}",
            url: "${githubSSHURL}"

        withCredentials([sshUserPrivateKey(credentialsId: "${githubKey}", keyFileVariable: 'CERT')]) {
            sh ("""
                mkdir -p ~/.ssh && chmod 700 ~/.ssh &&  cp -prf ${CERT} ~/.ssh/id_rsa && chmod 600 ~/.ssh/id_rsa
                git config --global --add safe.directory '/var/jenkins_home/workspace/mini-project'
                git config --global user.email ${githubEmail}
                eval `ssh-agent -s` && ssh-add ~/.ssh/id_rsa
                ssh-keyscan -H github.com >> ~/.ssh/known_hosts
                sed -i 's/tag:.*/tag: ${imageTag}/g' ${directoryPath}/helm-charts/values.yaml
                git add ${directoryPath}/helm-charts/values.yaml
                git commit -m '${commitMsg}'
                git push -u origin ${branch}
            """)
        }
    }
}
